export const CONSTANTS = {
  FINNHUB_API_KEY: 'cdj43n2ad3i9g9q04m90cdj43n2ad3i9g9q04m9g',
  ROCKET_MONEY_CATEGORIES: [
    'Uncategorized',
    'Cash & Checks',
    'Dining & Drinks',
    'Shopping',
    'Investment',
    'Travel & Vacation',
    'Medical',
    'Fees',
    'Bills & Utilities',
    'Internal Transfers',
    'Education',
    'Auto & Transport',
    'Groceries',
    'Entertainment & Rec.',
    'Business',
    'Income',
    'Personal Care',
    'Home & Garden',
    'Health & Wellness',
    'Software & Tech',
    'Loan Payment',
    'Credit Card Payment',
    'Family Care',
    'Taxes',
    'Pets',
    'Savings Transfer',
  ],
  ROCKET_MONEY_ACCOUNT_TYPES: {
    CASH: 'Cash',
    CREDIT_CARD: 'Credit Card',
  },
  CHART_COLORS: {
    RED: 'rgb(255, 0, 0)',
    GREEN: 'rgb(0, 255, 0)',
    BLUE: 'rgb(0, 0, 255)',
    YELLOW: 'rgb(255, 255, 0)',
    TEAL: 'rgb(0, 255, 255)',
    PINK: 'rgb(255, 0, 255)',
  },
};
